### ISSUE TITLE
Passthrough for completions and chat/completions

### ISSUE THREAD

**Issue by bioshazard** [limcheekin/open-text-embeddings#13]
> Many open source projects support the compatibility of the completions and the chat/completions endpoints of the OpenAI API, but do not support the embeddings endpoint 

I use `llama-cpp-python` for completions, but wish it supported these embedding-specific models. Now this project comes along and gives me that part! If this project does not intend to deliver completions, would you consider enabling a passthrough backend to serve the completions?

That would allow me to run this project in the front and have it pass through completion requests to `llama-cpp-python` and finally give me a complete OpenAI compatible solution for both embeddings AND completions without inferior completions from models not purposed for embeddings or changing based on the flavor-of-the-week model I have loaded for completions.

**Comment by limcheekin** [comment]
I'm an active user of the `llama-cpp-python` package too. In fact, this project is created when I find out that the package will not support the better open source embedding models such as:
- [BAAI/bge-large-en](https://huggingface.co/BAAI/bge-large-en)
- [intfloat/e5-large-v2](https://huggingface.co/intfloat/e5-large-v2)
- [sentence-transformers/all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2)
- [sentence-transformers/all-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2)

Sorry to tell you that I think implement a passthrough backend for `completions` just make the code base more complicated unnecessary. A simple way is just deploy the `embeddings` endpoint and `completions` endpoint as separate API. That's what I did. 

If you need all-in-one solution, you may check out https://localai.io/.

Hope this help.

**Comment by bioshazard** [comment]
@limcheekin , I understand the decision and appreciate the resource links. I will absolutely check out localai tytyty
