### ISSUE TITLE
how to load local model?

### ISSUE THREAD

**Issue by mrxf** [limcheekin/open-text-embeddings#4]
I have download bge model, how can I load the model from local?

**Comment by limcheekin** [comment]
Please see the following description at https://github.com/limcheekin/open-text-embeddings#standalone-fastapi-server.

Just replace the e5 model with bge model will do, for example: 
`MODEL=BAAI/bge-small-en-v1.5 NORMALIZE_EMBEDDINGS=1 DEVICE=cpu python -m open.text.embeddings.server`
