### ISSUE TITLE
Must provide an 'engine' or 'deployment_id'

### ISSUE THREAD

**Issue by d5423197** [limcheekin/open-text-embeddings#6]
Hello author,

I am trying to use this repo as an embedding model backend.  This error was raised. Can you help me with that?

Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>

Thanks,

**Comment by limcheekin** [comment]
Thanks for using the package. May I know the version of the `openai` package you used? Did you try to run the Colab of the demo?

**Comment by d5423197** [comment]
Hello there,

I am using openai version '0.27.9'. I am not using the colab. I am trying to use it in my project.

Thanks

**Comment by limcheekin** [comment]
Are you trying to use it with LangChain Python?

I just tried with the colab of the repo, it is working fine with openai v0.28.1.

If you're using the package with LangChain, you may need to use the `from open.text.embeddings.openai import OpenAIEmbeddings` class come with the package or report the issue to langchain repo if the problem happened to latest version of LangChain.

Hope this help.

**Comment by limcheekin** [comment]
Did my answer resolved the issue?

**Comment by d5423197** [comment]
Hello there,

I accidentally used the real openai key. This is the bug I found to solve this issue.

Thanks for your help

ZD

**Comment by limcheekin** [comment]
Alright, I will close the issue.
