### ISSUE TITLE
how to handle non-string embeddings request?

### ISSUE THREAD

**Issue by yangboyd** [limcheekin/open-text-embeddings#8]
how to handle such embeddings request?

{"input": [[6719, 263,  ], "model": "text-embedding-ada-002", "encoding_format": "base64"}

Seems like unicode.

**Comment by limcheekin** [comment]
Are you sure the integer array is not `Uint8Array`?

Non-string embeddings is not supported, please see my conversation with Bing Chat at https://sl.bing.net/hWYWlA7IzRs

I hope this help.

**Comment by limcheekin** [comment]
Do you have any question? Otherwise I will close the issue.

**Comment by limcheekin** [comment]
No response for weeks.
